webtalk_init -webtalk_dir D:/BELGELER/PROJERLER/VVADO/VERLOG/clk_divider_and_counter/clk_divider_and_counter.sim/sim_1/behav/xsim/xsim.dir/count_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jan  8 13:19:40 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211807344_0_0_146" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a98cda3a0d464be1b8e8d5b46d5422fe" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2712 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1310 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5884_KB" -context "xsim\\usage"
webtalk_transmit -clientid 783019497 -regid "211807344_0_0_146" -xml D:/BELGELER/PROJERLER/VVADO/VERLOG/clk_divider_and_counter/clk_divider_and_counter.sim/sim_1/behav/xsim/xsim.dir/count_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/BELGELER/PROJERLER/VVADO/VERLOG/clk_divider_and_counter/clk_divider_and_counter.sim/sim_1/behav/xsim/xsim.dir/count_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/BELGELER/PROJERLER/VVADO/VERLOG/clk_divider_and_counter/clk_divider_and_counter.sim/sim_1/behav/xsim/xsim.dir/count_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
