set_property PACKAGE_PIN W5 [get_ports clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]
 
set_property PACKAGE_PIN U16 [get_ports {counter[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {counter[0]}]
set_property PACKAGE_PIN E19 [get_ports {counter[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {counter[1]}]
set_property PACKAGE_PIN U19 [get_ports {counter[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {counter[2]}]
set_property PACKAGE_PIN V19 [get_ports {counter[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {counter[3]}]
set_property PACKAGE_PIN W18 [get_ports {counter[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {counter[4]}]
set_property PACKAGE_PIN U18 [get_ports rst]						
	set_property IOSTANDARD LVCMOS33 [get_ports rst]
